version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "22:00"
  open-pull-requests-limit: 10
  assignees:
    - "octocat"
  commit-message:
    # Prefix all commit messages with "npm"
    prefix: "npm"
  reviewers:
    - "selfpub-org/selfpub_frontend"
  labels:
    - "dependencies"
  ignore:
  - dependency-name: styled-components
    versions:
    - ">= 4.4.a"
    - "< 4.5"
